name: CI/CD Pipeline

on:
  push:
    branches:
      - "docker"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Build and Push Spring Boot App Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ergasiaapp:spring-boot-app-latest

      -
        name: Build and Push React App Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./react-frontend
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ergasiaapp:react-app-latest

      -
        name: Build and Push Database Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfile-db
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ergasiaapp:database-latest
